xmppIdentity.ldif: ITU-T H.350.7 (01/2007) -- LDIF module extracted from ITU-T H.350.7 (01/2007)# XmppURIObject Object Schema
#
# Schema for representing a XmppURIObject Object in an LDAP Directory
# 
# Abstract
# 
# This document defines the schema for representing XmppURIObject 
# object in an LDAP directory [LDAPv3].  It defines schema elements
# to represent an XmppURIObject object [XmppURIObject].
# 
#                     .1 = Communication related work
#                     .1.9 = XmppURIObject
#                     .1.9.1 = attributes
#                     .1.9.2 = objectclass
#                     .1.9.3 = syntax
#
#
#
# Attribute Type Definitions
# 
#    The following attribute types are defined in this document:
# 
#     XmppIdentityURI
#     XmppUserId
#     XmppPassword
dn: cn=schema 
changetype: modify 
#
# if you need to change the definition of an attribute, 
#            then first delete and re-add in one step
#
# if this is the first time you are adding the genericIdentity
# objectclass using this LDIF file, then you should comment
# out the delete attributetypes modification since this will
# fail. Alternatively, if your ldapmodify has a switch to continue
# on errors, then just use that switch -- if you're careful
#
delete: attributetypes
attributetypes:(0.0.8.350.1.1.9.1.1 NAME 'XmppIdentityURI' ) 
attributetypes:(0.0.8.350.1.1.9.1.2 NAME 'XmppUserId' ) 
attributetypes:(0.0.8.350.1.1.9.1.3 NAME 'XmppPassword' ) 
-
#
# re-add the attributes -- in case there is a change of definition
#
# 
add: attributetypes 
attributetypes: (0.0.8.350.1.1.9.1.1 
     NAME 'XmppIdentityURI' 
     DESC 'Labeled URI format to represent an XMPP URI' 
     EQUALITY caseIgnoreMatch  
     EQUALITY caseIgnoreSubstringsMatch  
     SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 ) 
attributetypes: (0.0.8.350.1.1.9.1.2 
     NAME 'XmppUserId' 
     DESC 'Xmpp Userid' 
     EQUALITY caseIgnoreMatch 
     EQUALITY caseIgnoreSubstringsMatch 
     SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 ) 
attributetypes: (0.0.8.350.1.1.9.1.3 
     NAME 'XmppPassword' 
     DESC 'Xmpp password' 
     EQUALITY octetStringMatch  
     SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 ) 
-
# Object Class Definitions
# 
#    The following object class is defined in this document:
# 
#        XmppURIObject
# 
# XmppURIObject
#  
#
delete: objectclasses
objectclasses: (0.0.8.350.1.1.9.2.1 NAME 'XmppURIObject' ) 
-
add: objectclasses 
objectclasses: (0.0.8.350.1.1.9.2.1 
        NAME 'XmppURIObject' 
        DESC 'XmppURI  object' 
        SUP top AUXILIARY 
        MAY ( XmppIdentityURI $ XmppUserId $ XmppPassword ) 
        ) 
-
#
# end of LDIF
#
